version: '3'
services:
    postgres:
        image: postgres
        container_name: postgres_db
        environment:
            POSTGRES_USERNAME: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - 5432:5432
        volumes:
            - database_data:/var/lib/postgresql/data
    backend:
        build: ./backend
        container_name: finance-backend
        image: jodonogh/finance-backend
        ports:
            - ${API_PORT}:5000
        volumes:
            - ./backend:/root/backend:cached
        depends_on:
            - postgres
    ngrok:
        image: wernight/ngrok
        command: ['ngrok', 'http', 'backend:5000']
        ports:
            - ${NGROK_PORT}:4040
        depends_on:
            - backend
    frontend:
        container_name: finance-frontend
        build: ./frontend
        image: jodonogh/finance-frontend
        # command: sh -c "npm install && npm start"
        # working_dir: /root/frontend
        ports:
            - ${CLIENT_PORT}:3000
        volumes:
            - ./frontend:/root/frontend:cached
        depends_on:
            - backend
volumes:
    database_data:
